### ISSUE TITLE
Fix tests with Joint trainer save

### ISSUE THREAD

**Issue by bbaranow** [Novartis/ChemBioMultimodalAutoencoders#2]
There is a problem with Joint Trainer tests in pytest. Please take a look at:

https://github.com/Novartis/ChemBioMultimodalAutoencoders/actions/runs/4973943352/jobs/8900106956

**Comment by bbaranow** [comment]
you can use the branch small_fixes_before_release

**Comment by ThibaultBechtler** [comment]
Fixed the issue with commit 9df55b2. Forgot to remove some code from joint_trainer._resume_from_file after moving a few things from the calss initialization to the train function.

**Comment by ThibaultBechtler** [comment]
There is another issue with the test. Will fix it later today.

**Comment by ThibaultBechtler** [comment]
Bug now really fixed in 4a29ccd. Actions for py3.9 and py3.10 finished without errors.
